amcl:
  ros__parameters:
    base_frame_id: base_footprint
    odom_frame_id: odom
    global_frame_id: map
    scan_topic: /scan_raw
    tf_broadcast: true

map_server:
  ros__parameters:
    yaml_filename: /home/wim/Documents/social_momentum_venv/social_momentum_MPPI/src/tiago_social_scenarios/maps/hallway_map.yaml
